allowBuilds:
  '@parcel/watcher': true
  core-js: true
  core-js-pure: true
  fs-ext-extra-prebuilt: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - '@aarsteinmedia/dotlottie-player@6.3.11 || 6.3.12 || 6.3.13'
  - '@aarsteinmedia/lottie-web@1.5.1 || 1.5.2 || 1.5.3'
  - eslint-plugin-perfectionist@5.10.1
